name: Feature Branch

on:
  push:
    branches:
      - 'main'

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Package
        working-directory: agent-user-service
        run: mvn -B clean package -DskipTests
#       - name: Maven Verify
#         working-directory: agent-user-service
#         run: mvn -B clean verify


      - name: Publish - GitHub Packages
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Publish artifact on GitHub Packages
        run: mvn -B clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
